version: 2

models:
  - name: dim_customer
    description: "Dimension client"
    columns:
      - name: customer_id
        tests:
          - not_null
  - name: dim_product
    description: "Dimension Produit"
    columns:
      - name: product_id
        tests:
          - not_null